services:
  - type: web
    name: krazy-kanban
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    preDeployCommand: cd server && npx sequelize-cli db:migrate --env production && npx sequelize-cli db:seed:all --env production
